username: "iampraveena1988@gmail.com"
password: "SL3E4QWjxZpyDGg!"
pool_id: "us-east-1_uKUKpqppE"
client_id: "5fqcn5kfa3iii799jdpj1viu86"
region_name: "us-east-1"
idp-host: "cognito-idp"
host: "oc9rczvetg.execute-api.us-east-1.amazonaws.com"
tenant_id: "TNTG_JcAiNzE5f6aAju"
experience_id: "EXP_sJwycXmM4uvjNCWFnEUdxc85T"
endPoints:
  login: "/qa/apheleia/user"
  authorize: "/qa/apheleia/user-audit"
  listTenants: "/qa/apheleia/tenant/search"
  fetch-nav: "/qa/apollo/web-view/{}/navs"
  list-categories: "/qa/experiences/unique-categories/{}"
  search: "/qa/experiences/search/{}"
  switch-tenants: "/qa/apollo/signed-urls"
  list-experiences: "/qa/apollo/signed-urls"
  Open-update-experience: "/qa/experiences/update/{}/{}"
  add-object-mesh: "/qa/editor-records/search/{}"